Luigi cookbook
chaordic/chef-luigi pull request #1
Opened 2017-01-30 20:12 UTC by gmendonca

Creating luigi cookbook.

2017-02-01 19:53 UTC, barata requested changes

2017-02-01 19:53 UTC, barata commented on templates/default/luigi-server.init.erb
> +[ -r /etc/default/$NAME ] && . /etc/default/$NAME
Does it make sense to create `luigi-env.sh.erb` in `/etc/default/luigid`?
If so, we could define attributes like `default['luigid']['env']['VALUE']` to be include in the template file.

2017-02-01 19:53 UTC, barata commented on templates/default/client.cfg.erb
> +db_connection = sqlite:///<%= @luigi_sqlite %>
What if we want to support JDBC? Is it possible?

2017-02-01 19:53 UTC, barata commented on templates/default/client.cfg.erb
> +record_task_history = True
Always `True`? Can we use lowercase?

2017-02-01 19:53 UTC, barata commented on templates/default/client.cfg.erb
> +[scheduler]
Is there other properties besides these? Can we generalize this file?

2017-02-01 19:53 UTC, barata commented on recipes/default.rb
> +  notifies  :start, 'service[luigid]'
`notifies  :start, 'service[luigid]' if node['luigid']['auto_start']`

2017-02-01 19:53 UTC, barata commented on recipes/default.rb
> +directory node['luigi']['dir'] do
What if `node['luigi']['user']` or `node['luigi']['group']` does not exist?

2017-02-01 19:53 UTC, barata commented on attributes/default.rb
> +default['luigid']['dir'] = '/mnt/luigid'
This structure sounds strange. It is not clear what goes inside `default['luigid']['dir']`

2017-02-02 14:13 UTC, gmendonca commented on templates/default/client.cfg.erb
> +db_connection = sqlite:///<%= @luigi_sqlite %>
Couldn't find anything out of the configuration.

2017-02-02 16:11 UTC, gmendonca commented on templates/default/client.cfg.erb
> +record_task_history = True
Python uses `True` not `true`.

2017-02-02 17:04 UTC, mwconceicao commented on templates/default/luigi-server.init.erb
> +#! /bin/sh
Consider creating systemd unit config for systems that moved to systemd (like Ubuntu 16.04).

2017-02-02 17:43 UTC, gmendonca commented
@barata what do you think now?

2017-02-03 17:00 UTC, barata requested changes
A lot of changes.

2017-02-03 17:00 UTC, barata commented on attributes/default.rb
> +default['luigi_server']['pid_file'] = '/usr/local/var/luigid.pid'
Usually we use `/var/run/luigid.pid`.

2017-02-03 17:00 UTC, barata commented on attributes/default.rb
> +default['luigi_server']['log_dir'] = '/usr/local/var/log'
Usually we use `/var/log/<app>`.

2017-02-03 17:00 UTC, barata commented on attributes/default.rb
> +default['luigi_server']['auto_start'] = true
What about `default['luigi']['server']['auto_start']`?

2017-02-03 17:00 UTC, barata commented on attributes/default.rb
> +  'record_task_history' = True, # Python syntaxe
This has nothing to do with python. This is ruby, and that's it :)

2017-02-03 17:00 UTC, barata commented on attributes/default.rb
> +default['client_cfg']['scheduler'] = {
```
default['luigi'][client_cfg] = {
  'scheduler' => {
    'record_tasl_history' => true,
    'state_path' => '/usr/local/var/luigi-state.pickle'
  },
  'task_history' => {
    'db_connection' => 'sqlite:////usr/local/var/luigi-task-hist.db'
  }
}
```

2017-02-03 17:00 UTC, barata commented on recipes/default.rb
> +include_recipe 'python'
Move this close to where it is used.

2017-02-03 17:00 UTC, barata commented on recipes/default.rb
> +
Define an attribute `luigi.setup_user` and create one here if it is true.
(The same applies for group).

2017-02-03 17:00 UTC, barata commented on recipes/default.rb
> +  owner     node['luigi']['user'] || 'root'
Do you really need this `||`?

2017-02-03 17:00 UTC, barata commented on recipes/default.rb
> +  owner     node['luigi']['user'] || 'root'
Do you need this `||`?

2017-02-03 17:00 UTC, barata commented on recipes/default.rb
> +directory node['luigi_server']['log_dir'] do
enable recursive dir creation.

2017-02-03 17:00 UTC, barata commented on recipes/default.rb
> +  action :nothing
`action :enable`

2017-02-03 17:00 UTC, barata commented on recipes/default.rb
> +  notifies  :enable, 'service[luigid]'
I think you can remove this.

2017-02-03 17:00 UTC, barata commented on recipes/default.rb
> +  notifies  :start, 'service[luigid]' if node['luigid']['auto_start']
`luigid` does not exist. :-(

2017-02-03 17:00 UTC, barata commented on templates/default/luigi-server.init.erb
> +	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
`--test`?

2017-02-03 17:00 UTC, barata commented on templates/default/luigi-server.init.erb
> +DAEMON_ARGS="--background --pidfile $PIDFILE --logdir $LOGDIR"
`--pidfile` is duplicated. Please check which one is really necessary.

2017-02-03 17:00 UTC, barata commented on templates/default/luigi-server.init.erb
> +		$DAEMON_ARGS \
`--pidfile` is also defined on `$DEAMON_ARGS`.

2017-02-03 17:36 UTC, gmendonca commented on recipes/default.rb
> +  action :nothing
I saw [this](http://stackoverflow.com/questions/9938314/chef-how-to-run-a-template-that-creates-a-init-d-script-before-the-service-is-c) thread, that's why I kept nothing here.

2017-02-03 17:50 UTC, barata commented on recipes/default.rb
> +  action :nothing
If it doesn't work, put this `service` statement right after `template` creation below. But I'd first try it here.

2017-02-03 17:52 UTC, barata commented on recipes/default.rb
> +group node['luigi']['group'] do
You need to associate the user to this group.
First create the group, then create the user referencing this group.

2017-02-06 19:29 UTC, gmendonca commented
@barata everything has been testes. I think we're all set here.

2017-02-07 12:59 UTC, barata requested changes

2017-02-07 12:59 UTC, barata commented on attributes/default.rb
> +default['luigi']['server']['create_dir'] = true
I think this parameter is not necessary. If `luigi.server.dir` does not exist, we always create it, that's it.

2017-02-07 12:59 UTC, barata commented on recipes/default.rb
> +group node['luigi']['group'] do
I think I've already said that. But again... you need to associate luigi user to luigi group.

2017-02-07 12:59 UTC, barata commented on recipes/default.rb
> +directory node['luigi']['config_dir'] do
`recursive`?

2017-02-07 12:59 UTC, barata commented on recipes/default.rb
> +  mode      '0755'
644? (rw, r, r)

2017-02-07 12:59 UTC, barata commented on recipes/default.rb
> +  mode      '0755'
directories need `x` permission, config files don't.

2017-02-07 12:59 UTC, barata commented on recipes/default.rb
> +  only_if { node['luigi']['server']['create_dir'] }
dont think we need this.

2017-02-07 12:59 UTC, barata commented on recipes/default.rb
> +directory node['luigi']['server']['dir'] do
`recursive`?

2017-02-07 12:59 UTC, barata commented on recipes/default.rb
> +  source    'client.cfg.erb'
did you really test this? Oo

2017-02-07 13:56 UTC, gmendonca commented
@barata

2017-02-07 14:19 UTC, barata approved these changes

2017-02-07 14:34 UTC, merged